---
  - name: setup frontend stack
    cloudformation:
      stack_name: "{{application}}-{{ab}}-{{version}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/frontend-alb.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BusinessUnit: "{{business_unit}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        ECRRegistry: "{{deployment_ecr}}"
        HpECRRepo: "{{hp_ecr_repo}}"
        HpBuildEcr: "{{ buildkite_build_ecr }}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{key_name}}"
        MaxSize: "{{max_asg_size}}"
        MinSizeAS: "{{min_asg_size}}"
        NewRelicRPM: "{{new_relic_rpm}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
        PagerDutyArn: "{{low_pager_duty_arn}}"
        HPagerDutyArn: "{{high_pager_duty_arn}}"
        RecordName: "{{application}}-{{ab}}-{{version}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        SSLCertificateARN: "{{ssl_cert_arn}}"
        SubnetID: "{{private_subnets}}"
        VPC: "{{aws_vpc_id}}"
        VpcCidr: "{{vpc_cidr}}"
        VpcDns: "{{vpc_dns}}"
        HpserviceCount: "{{hp_service_count}}"
        Env: "{{env}}"
        Version: "{{version}}"
        InstProfile: "{{instance_profile_role}}"
        Project: "{{project}}"
        Hptaskmem: "{{hp_task_mem}}"
        Hptaskcpu: "{{hp_task_cpu}}"
        AwslogsGroupHp: "{{logs_group_hp}}"
        AlbLoadBalancer: "{{alb_load_balancer}}"
        HpTargetGroupPort: "{{hp_tg_port}}"
      tags:
        Project: "{{project}}"
        application: "{{application}}"
        lob: "id"
        env: "{{env}}"
        stack_name: "{{application}}-{{ab}}-{{version}}"
        Business Unit: "{{business_unit}}"
