---
  - name: delete subscription
    command: aws logs delete-subscription-filter --log-group-name {{ logs_group_hp }} --filter-name {{ subscription_filter.stdout }} --region {{ aws_region }}

  - name: get lambda function arn
    command: aws lambda get-function --function-name "newlaunch-{{ env }}-{{ version }}-lambdafunction" --region {{ aws_region }} --query Configuration.FunctionArn --output text
    register: lambda_function_arn

  - name: add new subscription
    command: aws logs put-subscription-filter --log-group-name {{ logs_group_hp }} --destination-arn {{ lambda_function_arn.stdout }} --filter-name "LambdaStream-newlaunch-{{ env }}-{{ version }}-lambdafunction" --filter-pattern '' --region {{ aws_region }}