---
  - name: Set up an Application Load Balancer
    cloudformation:
      stack_name: "{{alb_name}}-alb"
      state: present
      region: "{{aws_region}}"
      template: "cloudformation/alb.yml"
      template_parameters:
        VpcID: "{{aws_vpc_id}}"
        Subnets: "{{public_subnets}}"
        LoadBalancerName: "{{alb_name}}"
        Scheme: "{{scheme}}"
        HealthCheckPath: "{{healthcheck_path}}"
        TargetGroupName: "{{target_group_name}}"
