steps:
  - label: ":construction: singapore-staging: create stack"
    command: './scripts/frontend-create-stack.sh'
    branches: 'master'
    env:
      ENV: stag
      ENV_INT: stag
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"
    concurrency: 1
    concurrency_group: 'Frontend-stack/deploy'
  - wait
  - label: ":arrows_clockwise: singapore-staging: switch stack"
    command: "./scripts/frontend-switch.sh"
    branches: 'master'
    env:
      ENV: stag
      ENV_INT: stag
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"
  - wait
  - label: ":wastebasket: singapore-staging: cleanup stack"
    command: "./scripts/frontend-cleanup.sh"
    branches: 'master'
    env:
      ENV: stag
      ENV_INT: stag
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"
  - wait
  - block: ':pagerduty: deploy-production-sg'

  - label: ":construction: singapore-production: create stack"
    command: './scripts/frontend-create-stack.sh'
    branches: 'master'
    env:
      ENV: prod-sg
      ENV_INT: prod
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"
  - wait

  - block: ':pagerduty: switch-production'
  - wait
  - label: ":arrows_clockwise: singapore-production: switch stack"
    command: "./scripts/frontend-switch.sh"
    branches: 'master'
    env:
      ENV: prod-sg
      ENV_INT: prod
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"

  - block: ':pagerduty: Clean-production'
  - wait
  - label: ":wastebasket: singapore-production: cleanup stack"
    command: "./scripts/frontend-cleanup.sh"
    branches: 'master'
    env:
      ENV: prod-sg
      ENV_INT: prod
      REGION: ap-southeast-1
      BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_ECR}"
    agents:
      queue: "api-enquiries-ipp:ci"
