dns_hostname: web
business_unit: ID
application: front-newlaunch-api
ab: "{{ env }}"
ecs_instance_type: t2.small
build: latest
min_asg_size: 1
max_asg_size: 3
desired_asg_capacity: 1

instance_profile_role: EC2-Role-Instance-Profile

low_pager_duty_arn:
high_pager_duty_arn:
ssl_cert_arn:

hp_ecr_repo: "{{ ecr_name }}"
hp_service_count: "{{ min_asg_size }}"
hp_task_mem: 1936
hp_task_cpu: 900
logs_group_hp: awslogs-stag-newlaunch-api-id

resource_bucket_name: enquiries.api.iproperty.com-prod

sumo_logic_access_id: su37UzMYy9KsP0
sumo_logic_access_key: aR2sAGxpvTuBHgRb6HcgygTPynv2wpRnjuQ4OgBt9zEBGcnXLAvhTMVCuY719uLf
new_relic_rpm: newrelic-sysmond-2.3.0.132-1.x86_64.rpm
new_relic_license_key: 566728cdfcce12ad0fef0741a0b24d5bbd4ee3df

deployment_ecr: "{{ account_arns }}.dkr.ecr.ap-southeast-1.amazonaws.com"
buildkite_build_ecr: latest

alb_load_balancer: arn:aws:elasticloadbalancing:ap-southeast-1:726150208279:loadbalancer/app/newlaunch-api-id-alb-stag/413a99f4de2a5086 #newlaunch-api-id-alb-stag
hp_tg_port: 81
sumologic_collector_endpoint: https://collectors.au.sumologic.com/receiver/v1/http/ZaVnC4dhaV3oV9kialNFiV4lyv6qUpUyCOjVtOxLf844YOV5g3F1zJzu9-hNRZkgstTyzEm9zXiheaj-Q91IwwSP1ZnijY24v_u4i-hiK3vh9nwbpHKLGw==