dns_hostname: web
business_unit: ID
Costcode: 502
application: front-newlaunch-api
ab: "{{ env }}"
ecs_instance_type: t2.small
build: latest
min_asg_size: 1
max_asg_size: 3
desired_asg_capacity: 1

instance_profile_role: EC2-Role-Instance-Profile

low_pager_duty_arn:
high_pager_duty_arn:
ssl_cert_arn:

hp_ecr_repo: "{{ ecr_name }}"
hp_service_count: "{{ min_asg_size }}"
hp_task_mem: 1936
hp_task_cpu: 900
logs_group_hp: awslogs-stag-newlaunch-api-id

resource_bucket_name: enquiries.api.iproperty.com-prod

sumo_logic_access_id: su37UzP0
sumo_logic_access_key: aR2sAGxpvTuBHgRb6HcgygBt9zEBGcnXLAvhTMVCuY719uLf ##  Need to verify

new_relic_license_key: AQICAHj1keVeoA9wgQiW1BgXe6UsTUpVjgI7V6Mt9byC0bH+PQGTngzwJufitleBeVQPKwzxAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNatzBwqvri+exxUVQIBEIBDisZhk0sB+yWgpjzkswgMoLJw0dnlunGinvGQwDkMUCEOmCtcRnGp2US4sMMPQ+Jc4w4TWtMmuKJ5sh5N6ykEQKv4HQ==

deployment_ecr: "{{ account_arns }}.dkr.ecr.ap-southeast-1.amazonaws.com"
buildkite_build_ecr: latest

alb_load_balancer: arn:aws:elasticloadbalancing:ap-southeast-1:726150208279:loadbalancer/app/newlaunch-api-id-alb-stag/413a99f4de2a5086 #newlaunch-api-id-alb-stag
hp_tg_port: 81
sumologic_collector_endpoint: https://collectors.au.sumologic.com/receiver/v1/http/ZaVnC4dhaV0zyFkmmM3bb32RVFESefiOyWZoxSL2iZBj73YzJHCp1PQ9uwplINcmdfRNzz2tPDibqcqx8KNEWsiGtkRAvNwEOLgV58yIlqrZ0ac36tgxcA==